[package]
name = "to-do_cli"
version = "0.1.0"
edition = "2024"
[[bin]]
name = "todo"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.100"
clap = {version = "4.5.48", features = ["derive"]}
serde = {version = "1.0.228", features = ["derive"]}
serde_json = "1.0.145"
